//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalizationTools.SampleProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalizationTools.SampleProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the city name.
        /// </summary>
        public static string CityDescription {
            get {
                return ResourceManager.GetString("CityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a business name.
        /// </summary>
        public static string Class1_Business_Please_enter_a_business_name {
            get {
                return ResourceManager.GetString("Class1_Business_Please_enter_a_business_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this is my {0} text.
        /// </summary>
        public static string Class1_Business_this_is_my__0__text {
            get {
                return ResourceManager.GetString("Class1_Business_this_is_my__0__text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Name.
        /// </summary>
        public static string Class1_City_My_Name {
            get {
                return ResourceManager.GetString("Class1_City_My_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new string.
        /// </summary>
        public static string Class1_MyProperty_A_new_string {
            get {
                return ResourceManager.GetString("Class1_MyProperty_A_new_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just a new string.
        /// </summary>
        public static string Class1_MyProperty_Just_a_new_string {
            get {
                return ResourceManager.GetString("Class1_MyProperty_Just_a_new_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just a new string.
        /// </summary>
        public static string Class1_MyProperty_Just_a_new_string1 {
            get {
                return ResourceManager.GetString("Class1_MyProperty_Just_a_new_string1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just a new string2.
        /// </summary>
        public static string Class1_MyProperty_Just_a_new_string2 {
            get {
                return ResourceManager.GetString("Class1_MyProperty_Just_a_new_string2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just a new string3.
        /// </summary>
        public static string Class1_MyProperty_Just_a_new_string3 {
            get {
                return ResourceManager.GetString("Class1_MyProperty_Just_a_new_string3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One more string 7.
        /// </summary>
        public static string Class1_MyProperty_One_more_string_7 {
            get {
                return ResourceManager.GetString("Class1_MyProperty_One_more_string_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceKey_MyProperty_Description.
        /// </summary>
        public static string Class1_MyProperty_ResourceKey_MyProperty_Description {
            get {
                return ResourceManager.GetString("Class1_MyProperty_ResourceKey_MyProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once again {AppName} some text.
        /// </summary>
        public static string Class1_MyProperty1_Once_again__AppName__some_text {
            get {
                return ResourceManager.GetString("Class1_MyProperty1_Once_again__AppName__some_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once again some text.
        /// </summary>
        public static string Class1_MyProperty1_Once_again_some_text {
            get {
                return ResourceManager.GetString("Class1_MyProperty1_Once_again_some_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dfghgher.
        /// </summary>
        public static string Class1_MyProperty4_dfghgher {
            get {
                return ResourceManager.GetString("Class1_MyProperty4_dfghgher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My other desription.
        /// </summary>
        public static string Class1_MyProperty4_My_other_desription {
            get {
                return ResourceManager.GetString("Class1_MyProperty4_My_other_desription", resourceCulture);
            }
        }
    }
}
